### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by GBULLR** [robren/sec_edgar_download#1]
* sec_edgar_download version:
* Python version:
* Operating System:

### Description

Could you please post an example of what to type after import sec_edgar_download to get the program to download AAPL's files for the last year for example.  
Thank you.

**Comment by robren** [comment]
Gaston,
Thanks for trying out the package. I've updated the README.rst to show a simple example for how to obtain the xbrl files for a single ticker for one year.

Let me know if this helps.

Regards 

Rob Rennison

**Comment by robren** [comment]
Updated the README with  another example. Closing the issue.
